### ISSUE TITLE
Loading configuration in .Net

### ISSUE THREAD

**Issue by niklaswarvik** [n2cms/n2cms#776]
After the the fix for #769 custom configurations for the ckeditor leads to a crash.
As far as I can see the problem is the cast to NameValueConfigurationElement in FreeTextArea and Host
as the collection is both of type KeyValueConfigurationCollection. 
In the ConfigurationBuilder the collection is of type NameValueCollection so that seems correct.

[FreeTextArea](https://github.com/n2cms/n2cms/blob/4e41aab0ed449a66c427599c470f508ece3982a7/src/Framework/N2/Web/UI/WebControls/FreeTextArea.cs#L193)
[Host](https://github.com/n2cms/n2cms/blob/4e41aab0ed449a66c427599c470f508ece3982a7/src/Framework/N2/Web/Host.cs#L163)

The crash can be reproduced by adding a ckeditor setting in the web.config and then add a Text part or any part which uses a EditableFreeTextAreaAttribute.

**Comment by bherila** [comment]
Do you have a stack trace handy @niklaswarvik

**Comment by niklaswarvik** [comment]
I have this stack trace for the FreeTextArea @bherila 

`
System.InvalidCastException was unhandled by user code
  HResult=-2147467262
  Message=Unable to cast object of type 'System.Configuration.KeyValueConfigurationElement' to type 'System.Configuration.NameValueConfigurationElement'.
  Source=N2
  StackTrace:
       at N2.Web.UI.WebControls.FreeTextArea.GetOverridesJson() in C:\Repo\n2cms\src\Framework\N2\Web\UI\WebControls\FreeTextArea.cs:line 193
       at N2.Web.UI.WebControls.FreeTextArea.OnPreRender(EventArgs e) in C:\Repo\n2cms\src\Framework\N2\Web\UI\WebControls\FreeTextArea.cs:line 97
       at System.Web.UI.Control.PreRenderRecursiveInternal()
       at System.Web.UI.Control.PreRenderRecursiveInternal()
       at System.Web.UI.Control.PreRenderRecursiveInternal()
       at System.Web.UI.Control.PreRenderRecursiveInternal()
       at System.Web.UI.Control.PreRenderRecursiveInternal()
       at System.Web.UI.Control.PreRenderRecursiveInternal()
       at System.Web.UI.Control.PreRenderRecursiveInternal()
       at System.Web.UI.Control.PreRenderRecursiveInternal()
       at System.Web.UI.Control.PreRenderRecursiveInternal()
       at System.Web.UI.Control.PreRenderRecursiveInternal()
       at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
`

**Comment by bherila** [comment]
Thank you, this is related to a change I made in an effort to move towards newer .NET classes. I think it should be a simple fix.

**Comment by bherila** [comment]
Actually, a code search on Github https://github.com/n2cms/n2cms/search?utf8=%E2%9C%93&q=KeyValueConfigurationElement&type=Code turns up no instances of `KeyValueConfigurationElement`

Any idea where it's coming from?

**Comment by bherila** [comment]
Another thought: It could be an N2 versioning conflict, if there are multiple versions of N2 packages installed in the same project.

**Comment by niklaswarvik** [comment]
When I reproduced the error I did so on a minimal installation. I created a new project and added N2 so only one version of N2 exists.

**Comment by bherila** [comment]
Can you double check the versions with `Get-Package` from the PowerShell command prompt?

**Comment by niklaswarvik** [comment]
This is the complete output.

  
| Id | Versions | ProjectName                               
| ------------- |:-------------:|-------------:|                                                                                             
|Iesi.Collections                    |{4.0.0.4000}              |               n2test                               |                                                                                
|Microsoft.ApplicationInsights |      {2.2.0}             |                     n2test                         |                                                                                      
|Microsoft.ApplicationInsights.Ag... |{2.0.6}            |                      n2test                        |                                                                                       
|Microsoft.ApplicationInsights.De... |{2.2.0}             |                     n2test                         |                                                                                      
|Microsoft.ApplicationInsights.Pe... |{2.2.0}              |                    n2test                          |                                                                                     
|Microsoft.ApplicationInsights.Web  | {2.2.0}            |                      n2test                   |                                                                                            
|Microsoft.ApplicationInsights.Wi... |{2.2.0}                |                  n2test                     |                                                                                          
|Microsoft.ApplicationInsights.Wi... |{2.2.0}               |                   n2test                    |                                                                                           
|Microsoft.AspNet.Mvc                |{5.2.3}                    |              n2test                       |                                                                                        
|Microsoft.AspNet.Razor             | {3.2.3}                 |                 n2test                      |                                                                                         
|Microsoft.AspNet.WebPages      |     {3.2.3}             |                     n2test                |                                                                                               
|Microsoft.CodeDom.Providers.DotN...| {1.0.0}         |                         n2test          |                                                                                                     
|Microsoft.Net.Compilers            | {1.0.0}                    |              n2test                   |                                                                                            
|Microsoft.Web.Infrastructure     |   {1.0.0.0}        |                        n2test               |                                                                                                
|N2CMS.Config                       | {2.6.2}                 |                 n2test                     |                                                                                          
|N2CMS.Config.SQLite             |    {2.9.6.17}         |                      n2test              |                                                                                                 
|N2CMS.Dinamico                    |  {2.9.6.17}          |                     n2test               |                                                                                                
|N2CMS.Library                     |  {2.9.6.17}             |                  n2test                 |                                                                                              
|N2CMS.Management           |         {2.9.6.17}      |                         n2test          |                                                                                                     
|N2CMS.Mvc                    |       {2.9.6.17}              |                 n2test                |                                                                                               
|N2CMS.Razor                   |      {2.9.6.17}              |                 n2test               |                                                                                                
|N2CMS.ReusableParts      |           {2.9.6.17}        |                       n2test         |                                                                                                      
|NHibernate                        |  {4.0.3.4000}            |                 n2test              |                                                                                                 
|SharpZipLib                   |      {0.86.0}                   |              n2test                |                                                                                               
|System.Data.SQLite.Core|             {1.0.104.0}       |                       n2test     |

**Comment by bherila** [comment]
I think this is fixed @niklaswarvik in the latest version, it is not reproducing for me. Please check and reopen if you are still having trouble.

Thanks,
Ben

**Comment by Gidmark** [comment]
Got the same problem. In https://github.com/n2cms/n2cms/blob/master/src/Framework/N2/Web/UI/WebControls/FreeTextArea.cs
This bit of code
`foreach (NameValueConfigurationElement setting in customConfig)`
Should probably be
`foreach (KeyValueConfigurationElement setting in customConfig)`

It seems like you only get it if you have actual settings for the ckeditor eg:
`<ckeditor contentsCssPath="~/v2/css/wysiwyg.css" ckConfigJsPath="/n2/ckconfig.js">
        <settings>
          <add key="stylesSet" value="my_styles:/n2/ckconfig.styles.js" />
        </settings>
      </ckeditor`

in my case

**Comment by niklaswarvik** [comment]
@bherila 
Hi, this is still an issue for me. As @Gidmark explained 
`<ckeditor contentsCssPath="~/v2/css/wysiwyg.css" ckConfigJsPath="/n2/ckconfig.js"> <settings> <add key="stylesSet" value="my_styles:/n2/ckconfig.styles.js" /> </settings> </ckeditor>`
needs to be inserted under the `<edit>` tag in the web.config. The error does not show up otherwise.

**Comment by DejanMilicic** [comment]
@niklaswarvik I will try to fix this in next few days

**Comment by DejanMilicic** [comment]
@niklaswarvik Can you please test this. Or if you cannot, can you please provide me with a configuration I can test so we are sure configuration is loaded and applied correctly

**Comment by niklaswarvik** [comment]
@DejanMilicic I have tested the solution and it seems to work for me. Thanks!

**Comment by Gidmark** [comment]
This seems to have come back, i just updated to 2.9.6.19 from 2.9.6.8 and now getting the same error again:

`[InvalidCastException: Unable to cast object of type 'System.Configuration.KeyValueConfigurationElement' to type 'System.Configuration.NameValueConfigurationElement'.]
   N2.Web.UI.WebControls.FreeTextArea.GetOverridesJson() in C:\Users\ucadmin\Documents\n2cms\src\Framework\N2\Web\UI\WebControls\FreeTextArea.cs:193
   N2.Web.UI.WebControls.FreeTextArea.OnPreRender(EventArgs e) in C:\Users\ucadmin\Documents\n2cms\src\Framework\N2\Web\UI\WebControls\FreeTextArea.cs:97
   System.Web.UI.Control.PreRenderRecursiveInternal() +88
   System.Web.UI.Control.PreRenderRecursiveInternal() +160
   System.Web.UI.Control.PreRenderRecursiveInternal() +160
   System.Web.UI.Control.PreRenderRecursiveInternal() +160
   System.Web.UI.Control.PreRenderRecursiveInternal() +160
   System.Web.UI.Control.PreRenderRecursiveInternal() +160
   System.Web.UI.Control.PreRenderRecursiveInternal() +160
   System.Web.UI.Control.PreRenderRecursiveInternal() +160
   System.Web.UI.Control.PreRenderRecursiveInternal() +160
   System.Web.UI.Control.PreRenderRecursiveInternal() +160
   System.Web.UI.Control.PreRenderRecursiveInternal() +160
   System.Web.UI.Control.PreRenderRecursiveInternal() +160
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +985`
